New Version 3.3.15

diff --git a/scripts/thecore_modules/create/app b/scripts/thecore_modules/create/app
--- a/scripts/thecore_modules/create/app
+++ b/scripts/thecore_modules/create/app
@@ -233,6 +233,7 @@ EOF
     rails webpacker:install
     rails active_storage:install
     rails action_text:install
+    rails action_mailbox:install
     rails g erd:install
     yarn install
     rails db:create
@@ -275,6 +276,54 @@ fi
 mkdir installers
 
 thecore create config localdev deployment
+
+# Add some script useful for CI/CD
+cat <<EOF | tee "bin/deploy.sh"
+#!/bin/sh -e
+
+if [ "$#" -ne 1 ]
+then
+    echo "ERROR! The first argument must exists and it has to be either docker_test_host or docker_host"
+    exit 1
+fi
+
+if ! [ -d installers ]
+then
+    echo "ERROR! This script must be run from the directory containing installers folder."
+    exit 2
+fi
+
+cd installers
+for PROVIDER in *
+do 
+if [ -f "$PROVIDER/$1" ]
+then
+    echo "$PROVIDER has a docker_test_host file, let's see if it also has customers"
+    export DOCKER_HOST="$(cat "$PROVIDER/$1")"
+    export DOCKER_HOST_DOMAIN="$(echo $DOCKER_HOST | cut -d'/' -f3 | cut -d':' -f1)"
+    export DOCKER_HOST_PORT="$(echo $DOCKER_HOST | cut -d'/' -f3 | cut -d':' -f2)"
+    ssh $DOCKER_HOST_DOMAIN -p $DOCKER_HOST_PORT "
+    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY; 
+    mkdir -p /tmp/installers; 
+    exit"
+    rsync -arvz -e "ssh -p $DOCKER_HOST_PORT" --progress --delete docker-compose.yml $PROVIDER ${DOCKER_HOST_DOMAIN}:/tmp/installers/
+    for CUSTOMER in $PROVIDER/*.env
+    do
+    echo "  - found $CUSTOMER doing the remote up thing on $DOCKER_HOST"
+    ssh $DOCKER_HOST_DOMAIN -p $DOCKER_HOST_PORT " 
+        export IMAGE_TAG_HELPDESK_SIDEKIQ=$IMAGE_TAG_HELPDESK_SIDEKIQ; 
+        export IMAGE_TAG_HELPDESK=$IMAGE_TAG_HELPDESK; 
+        export IMAGE_TAG_BACKEND=$IMAGE_TAG_BACKEND; 
+        export IMAGE_TAG_BACKEND_SIDEKIQ=$IMAGE_TAG_BACKEND_SIDEKIQ; 
+        cd /tmp/installers
+        docker-compose --env-file $CUSTOMER pull; 
+        docker-compose --env-file $CUSTOMER up -d --remove-orphans --no-build; 
+        exit"
+    done
+    ssh $DOCKER_HOST_DOMAIN -p $DOCKER_HOST_PORT "docker system prune -f; docker logout $CI_REGISTRY; exit" 
+fi
+done
+EOF
 
 echo "New Thecore App: ${FULLNAME} created."
 
diff --git a/scripts/thecore_modules/create/config/localdev/deployment b/scripts/thecore_modules/create/config/localdev/deployment
--- a/scripts/thecore_modules/create/config/localdev/deployment
+++ b/scripts/thecore_modules/create/config/localdev/deployment
@@ -309,6 +309,106 @@ bundle exec rails s -p 3000 -b '0.0.0.0'
 exit 0
 EOT
 
+cat <<EOF | tee "bin/down.sh"
+#!/bin/bash
+
+if ! [[ -d installers ]]
+then
+    echo -e "\e[31m\e[1mERROR! This Script is intended to be run from installer's parent directory."
+    exit 1
+fi
+
+if [[ $# -ne 3 ]]
+then
+    echo -e "\e[31m\e[1mERROR! This command accepts exactly 3 arguments:\e[0m"
+    echo "  $0 service customer type"
+    echo "  - service must be chosen among: $(ls installers | xargs)"
+    echo "  - customer must be chosen among: $(ls installers/**/*.env | xargs -n 1 basename | sed -e 's/\.env$//' | xargs)"
+    echo "  - type must be chosen between wet or dry: wet to apply the deploy, dry to just test the building."
+    exit 1
+fi
+
+if ! [[ -d installers/$1 ]]
+then
+    echo -e "\e[31m\e[1mERROR! installers/$1 must exist, configure the deploy, please\e[0m"
+    exit 1
+fi
+
+if ! [[ -f installers/$1/$2.env ]]
+then
+    echo -e "\e[31m\e[1mERROR! installers/$1/$2.env must exist, configure the deploy, please\e[0m"
+    exit 1
+fi
+
+if [[ $3 != "wet" ]] && [[ $3 != "dry" ]]
+then
+    echo -e "\e[31m\e[1mERROR! The third argument must be either wet or dry: wet to apply the deploy, dry to just test the building\e[0m"
+    exit 1
+fi
+
+cd installers
+
+if [ "$3" = "wet" ]
+then
+    docker-compose --env-file $1/$2.env down --remove-orphans
+
+    docker system prune -a -f --volumes
+    docker builder prune -a -f
+else
+    echo "Third parameter is not wet, so I destroy nothing!"
+fi
+EOF
+
+cat <<EOF | tee "bin/up.sh"
+#!/bin/bash -e
+
+if ! [[ -d installers ]]
+then
+    echo -e "\e[31m\e[1mERROR! This Script is intended to be run from installer's parent directory."
+    exit 1
+fi
+
+if [[ $# -ne 3 ]]
+then
+    echo -e "\e[31m\e[1mERROR! This command accepts exactly 3 arguments:\e[0m"
+    echo "  $0 service customer type"
+    echo "  - service must be chosen among: $(ls installers | xargs)"
+    echo "  - customer must be chosen among: $(ls installers/**/*.env | xargs -n 1 basename | sed -e 's/\.env$//' | xargs)"
+    echo "  - type must be chosen between wet or dry: wet to apply the deploy, dry to just test the building."
+    exit 1
+fi
+
+if ! [[ -d installers/$1 ]]
+then
+    echo -e "\e[31m\e[1mERROR! installers/$1 must exist, configure the deploy, please\e[0m"
+    exit 1
+fi
+
+if ! [[ -f installers/$1/$2.env ]]
+then
+    echo -e "\e[31m\e[1mERROR! installers/$1/$2.env must exist, configure the deploy, please\e[0m"
+    exit 1
+fi
+
+if [[ $3 != "wet" ]] && [[ $3 != "dry" ]]
+then
+    echo -e "\e[31m\e[1mERROR! The third argument must be either wet or dry: wet to apply the deploy, dry to just test the building\e[0m"
+    exit 1
+fi
+
+cd installers
+
+# Start the builds
+docker-compose --env-file $1/$2.env config
+docker-compose --env-file $1/$2.env pull
+# The build phase is no longer needed, the image is already in the container registry, ready to be spinned up after pulling
+# docker-compose --env-file $1/$2.env build
+
+# Thanks to the -e switch, the up is done only if the previous preparation steps are succesfull
+# and obviously only if a first param is given (just to have control on the type or run: dry or wet)
+[ "$3" = "wet" ] && docker-compose --env-file $1/$2.env up -d --remove-orphans
+EOF
+
 chmod +x vendor/backend/entrypoint*.sh
 
 exit 0
