New Version 3.3.6

diff --git a/scripts/thecore_modules/create/library b/scripts/thecore_modules/create/library
--- a/scripts/thecore_modules/create/library
+++ b/scripts/thecore_modules/create/library
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if ! [ -d ../dependencies ]
+then
+  echo "ERROR! This must be run from inside app directory and have a sibling directory called dependencies"
+  exit 1  
+fi
+
 for i in *.gemspec
 do
   if [[ -f "$i" ]]
